### ISSUE TITLE
command ruby vr fail

### ISSUE THREAD

**Issue by cedlemo** [Beagle123/visualruby#1]
Eric,

when I try to run this command : `ruby vr` I have the following error:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- require_all (LoadError)
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from vr:18:in `<main>'
```

I use ArchLinux x86_64 and ruby 2.3.1

**Comment by Beagle123** [comment]
Yea, sorry. I'm working on it now.  I'm new to git, and when I tried to upload everything, git omitted the vrlib library.
Thanks for getting back to me.  Your work is awesome.
Let me fix it, and I'll get back to you today.
Best,Eric 

```
  From: cedlemo <notifications@github.com>
```

 To: Beagle123/visualruby visualruby@noreply.github.com 
 Sent: Tuesday, May 24, 2016 12:21 PM
 Subject: [Beagle123/visualruby] command ruby vr fail (#1)

Eric,when I try to run this command : ruby vr I have the following error:/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- require_all (LoadError)
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from vr:18:in `<main>'
I use ArchLinux x86_64 and ruby 2.3.1—

**Comment by Beagle123** [comment]
Also, vr will require the require_all gem:

gem install require_all

Normally the visualruby gem install it.

**Comment by Beagle123** [comment]
Also, it requires the gtksourceview3 gem:

gem install gtksourceview3

**Comment by Beagle123** [comment]
Ok this is it:
gem install require_all
gem install gtksourceview3
then get the latest repo:
git clone git@github.com:Beagle123/visualruby.git vrfolder

cd vrfolder
ruby vr
ok?
Best Eric 

```
  From: cedlemo <notifications@github.com>
```

 To: Beagle123/visualruby visualruby@noreply.github.com 
 Sent: Tuesday, May 24, 2016 12:21 PM
 Subject: [Beagle123/visualruby] command ruby vr fail (#1)

Eric,when I try to run this command : ruby vr I have the following error:/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- require_all (LoadError)
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from vr:18:in `<main>'
I use ArchLinux x86_64 and ruby 2.3.1—

**Comment by cedlemo** [comment]
Ok my bad Eric, I didn't install the visualruby gem and just tried `ruby vr`. That is why it did not work.
Now I have another error:

```
ruby vr
/home/cedlemo/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2/deprecatable.rb:112:in `const_missing': uninitialized constant VR_Document::GladeGUI (NameError)
    from /home/cedlemo/.gem/ruby/2.3.0/gems/glib2-3.0.9/lib/glib2/deprecatable.rb:112:in `const_missing'
    from /home/cedlemo/Projets/Ruby/visualruby/bin/editor/VR_Document.rb:4:in `<class:VR_Document>'
    from /home/cedlemo/Projets/Ruby/visualruby/bin/editor/VR_Document.rb:2:in `<top (required)>'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/require_all-1.3.3/lib/require_all.rb:108:in `require'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/require_all-1.3.3/lib/require_all.rb:108:in `block in require_all'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/require_all-1.3.3/lib/require_all.rb:106:in `each'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/require_all-1.3.3/lib/require_all.rb:106:in `require_all'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/require_all-1.3.3/lib/require_all.rb:153:in `block in require_rel'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/require_all-1.3.3/lib/require_all.rb:152:in `each'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/require_all-1.3.3/lib/require_all.rb:152:in `require_rel'
    from vr:20:in `<main>'

```

As you can see I have the git version of the ruby-gnome2 gems so this is maybe the reason why it does not work.

I will try to test with just the 3.0.8 version.

**Comment by Beagle123** [comment]
Sorry for the hassle.  I believe that you just need to pull the project from git again.  I updated it yesterday.

You can check to see that you have the updated version by looking for a folder named vrlib under the visualruby root.  The error you showed is due to that folder being missing before.

If you look in the vr file that you're trying to run, you'll see these lines:

require 'require_all'
require_rel 'vrlib/lib/'
require_rel 'bin/'

So you need the require_all gem installed (and gtk3 gem).  Then its looking for the vrlib files to include in the project.

Thanks for taking the time to look at this.  I think you'll find it interesting.

Best,
Eric

**Comment by cedlemo** [comment]
> Sorry for the hassle

No problem, I try it, it doesn't work, I let you know, we try to make it works, I re try, the software works and has been improved, and so on. For me this is how open-source works. 

After the pull request I have seen dialog windows showing me the directories for VisualRuby projects then I had this message:

```
ruby vr
/home/cedlemo/Projets/Ruby/visualruby/vrlib/lib/GladeGUI.rb: line 156
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
/home/cedlemo/Projets/Ruby/visualruby/vrlib/lib/GladeGUI.rb: line 156
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
/home/cedlemo/.gem/ruby/2.3.0/gems/gobject-introspection-3.0.9/lib/gobject-introspection/loader.rb: line 554
   Gtk-MESSAGE **:GtkDialog mapped without a transient parent. This is discouraged.
/home/cedlemo/Projets/Ruby/visualruby/vrlib/lib/treeview/FileTreeView.rb:59:in `add_file': undefined method `[]=' for nil:NilClass (NoMethodError)
    from /home/cedlemo/Projets/Ruby/visualruby/vrlib/lib/treeview/FileTreeView.rb:24:in `refresh'
    from /home/cedlemo/Projets/Ruby/visualruby/bin/main/VR_Main.rb:80:in `load_project'
    from /home/cedlemo/Projets/Ruby/visualruby/bin/main/VR_Main.rb:56:in `before_show'
    from /home/cedlemo/Projets/Ruby/visualruby/vrlib/lib/GladeGUI.rb:406:in `show'
    from vr:23:in `<main>'
```

**Comment by Beagle123** [comment]
Hi cedlemo:

I think that I fixed that bug.  This program should be pretty stable, I've been using it for years.

If you clone the repo from git again, and try "ruby vr" again, it should work.  Howver, you will likely run into another problem:  You won't be able to run the example files in the visualruby directory because the vrlib gem which is not available on rubygems.

However, this is easy to get around.  When you click "Open Project" click on the "Select Folder" button, and select the folder for an example under the /home/cedlemo/Projets/Ruby/visualruby/examples directory.  These will run fine because they find the working copy of vrlib.

Everything works from that folder.  Ignore the /home/visualruby folder it makes on your machine.

Please bare with me.  I'd like to get you the code instead of just the gem.

Bring on Fail #3?

Thanks,
Eric

**Comment by cedlemo** [comment]
I have done the pull request and I have been able to open an example: the calculator. When I try to run it I have this error message:

```
/home/cedlemo/.gem/ruby/2.3.0/gems/vrlib-1.0.19/lib/GladeGUI.rb:154:in `add_from_file': /home/cedlemo/visualruby/examples/calculator/bin/glade/Calculator.glade: required gtk+ version 3.0, current version is 2.24 (GLib::Error)
    from /home/cedlemo/.gem/ruby/2.3.0/gems/vrlib-1.0.19/lib/GladeGUI.rb:154:in `load_glade'
    from /home/cedlemo/.gem/ruby/2.3.0/gems/vrlib-1.0.19/lib/GladeGUI.rb:378:in `show'
    from main.rb:19:in `<main>'
```

I haven't had the time to go further.

**Comment by Beagle123** [comment]
You're doing it right except you need to open an example under:

/home/cedlemo/Projets/Ruby/visualruby

not

/home/cedlemo/visualruby  (totally ignore this folder)

To open an example, click on "Open Project" then "Select Folder" button and find this:

/home/cedlemo/Projets/Ruby/visualruby/examples/calculator

When that folder is open click "Ok" and the project will open.  My working copy of everything is under:

/home/cedlemo/Projets/Ruby/visualruby

Best,
Eric
