### ISSUE TITLE
Visualruby depend on gtksourceview2 for which support has been dropped

### ISSUE THREAD

**Issue by cedlemo** [Beagle123/visualruby#10]
https://github.com/ruby-gnome2/ruby-gnome2/issues/714#issuecomment-222442594

You shouldn't use gtk2 or gtksourceview2. The standard is now Gtk3.

Regards

**Comment by Beagle123** [comment]
Yea, I found what you're talking about.  Everything should be updated to gtk3 in the latest github version.  The gem on rubygems.org is still gtk2, but I'm working to get the gtk3 version up ASAP.

**Comment by cedlemo** [comment]
thx
