### ISSUE TITLE
No support for Rubucop in the code editor

### ISSUE THREAD

**Issue by cedlemo** [Beagle123/visualruby#11]
Rubucop is a must have when I writte ruby code, it really helps me writting good code (not so bad at least) and follow the common rules (I guess you know those links): 
-    https://github.com/bbatsov/ruby-style-guide
-    https://github.com/bbatsov/rubocop

**Comment by Beagle123** [comment]
Thanks cediemo:

Cool links.  I've been reading the formatting stuff and tightening up my code.  I ran rubocop, and it spit out a million messages, mainly about tabs.  Its a cool idea.

Actually vr will support rubocop:  Just go to "Project Settings"  and under the run command, type in rubocop, then press "Run" button  :)

You inspired me to make a better "Open Project" box when I needed to clarify how to open the example projects under your vr folder.  Now, I've reprogrammed it.  I think you'll find it easier.  Also, you can set your own root, so you don't need to make it the home/visualruby folder.  It's a super-fast interface:

https://www.ruby-forum.com/topic/6878560#new

Just clone latest github version.

Last time we communicated, you only needed to open the examples under your code folder to get it to work.  Just go to "Tools" => "Global Settings" and set it to the folder where you run "ruby vr"    Let me know if this makes it easier.

When you get this going, you'll have a working copy of visualruby that it editing itself.  So if you press the run button, it will be running the code that you're looking at.

Best,
Eric
