### ISSUE TITLE
Error: cannot load such file -- cairo.so (LoadError)

### ISSUE THREAD

**Issue by jessethebuilder** [Beagle123/visualruby#26]
I see this error has come up before, but existing fixes have not worked. 

> $ ruby vr
> c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require
> ': cannot load such file -- cairo.so (LoadError)
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:5
> 5:in`require'
>         from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cairo-1.15.2-x64-mingw32/li
> b/cairo.rb:46:in `rescue in <top (required)>'
>         from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/cairo-1.15.2-x64-mingw32/li
> b/cairo.rb:42:in`<top (required)>'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:5
> 5:in `require'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:5
> 5:in`require'
>         from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/glib2-3.0.8-x64-mingw32/lib
> /glib2.rb:107:in `<top (required)>'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:5
> 5:in`require'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:5
> 5:in `require'
>         from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gobject-introspection-3.0.8
> -x64-mingw32/lib/gobject-introspection.rb:17:in`<top (required)>'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:5
> 5:in `require'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:5
> 5:in`require'
>         from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gtk3-3.0.8-x64-mingw32/lib/
> gtk3.rb:17:in `<top (required)>'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:1
> 35:in`require'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:1
> 35:in `rescue in require'
>         from c:/Ruby200-x64/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:1
> 44:in`require'
>         from vr:1:in `<main>'

Using ruby 2.0.0p648 (2015-12-16) [x64-mingw32]
Windows 8

My Gems: 

> **\* LOCAL GEMS ***

atk (3.0.8 x64-mingw32)
bigdecimal (1.2.0)
cairo (1.15.2 x64-mingw32)
cairo-gobject (3.0.8 x64-mingw32)
gdk3 (3.0.8 x64-mingw32)
gdk_pixbuf2 (3.0.8 x64-mingw32)
gio2 (3.0.8 x64-mingw32)
glib2 (3.0.8 x64-mingw32)
gobject-introspection (3.0.8 x64-mingw32)
gtk3 (3.0.8 x64-mingw32)
gtksourceview3 (3.0.8 x64-mingw32)
io-console (0.4.2)
json (1.7.7)
minitest (4.3.2)
pango (3.0.8 x64-mingw32)
pkg-config (1.1.7)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
require_all (1.3.3)
rsvg2 (3.0.8 x64-mingw32)
test-unit (2.0.0.0)

I am using this particular version of Ruby, because another fix suggested it. I have tried 1.9.3 and 2.1.5, with the same (or very similar) error.

**Comment by Beagle123** [comment]
Hi Jesse:

I got your message.  I'll work on it.  I'll try it on my Win 7 computer and get back to you.

Best,
Eric

**Comment by Beagle123** [comment]
Hi Jesse:

On my windows machine I installed ruby 2.0.0 and got the same error.  When I upgraded to 2.3.0, it worked fine.  So I guess they fixed it in the later versions.

Try installing 2.3.0, and I think it will work.  It only takes a few minutes to install and reinstall.

I'm upgrading it on a daily basis right now, so try playing with it, then getting the next version.  Be sure to reinstall the examples (look on the menu) when you upgrade visualruby so you know they're compatible.

Let me know how it goes.

Eric

**Comment by Beagle123** [comment]
Hi Jesse:

Did you get it to work?

**Comment by jessethebuilder** [comment]
No, and I had to move on. I went with jruby and swing.  Jesse Farmerjessethebuilder@yahoo.com360-670-9312http://anysoft.us

```
  From: Eric Cunningham <notifications@github.com>
```

 To: Beagle123/visualruby visualruby@noreply.github.com 
Cc: Jesse Farmer jessethebuilder@yahoo.com; Author author@noreply.github.com
 Sent: Thursday, June 23, 2016 10:11 PM
 Subject: Re: [Beagle123/visualruby] Error: cannot load such file -- cairo.so (LoadError) (#26)

Hi Jesse:Did you get it to work?—
