### ISSUE TITLE
New Project creates MyClass.glade which refers to GtkButtonBox which Glade cannot create

### ISSUE THREAD

**Issue by rubycoder** [Beagle123/visualruby#31]
Following along with the video on the homepage of visualruby.net, when I try to open MyClass.glade in Glade I get this error:

![image](https://cloud.githubusercontent.com/assets/437106/16753768/66f7f0b2-47a1-11e6-9acf-966fcb4585e2.png)

The generated MyClass.glade contains the text `object class="GtkButtonBox"`

When I try to create a similar glade file from scratch in Glade, it contains the text `object class="GtkVButtonBox"` (which does not generate an error)

I'm using VisualRuby 3.0.15, Ruby 2.3.0-p0, Glade 3.8.5 on Windows 7 Professional SP 1 64 bit

Thanks!!!

**Comment by Beagle123** [comment]
Hey:

Yea, you're using an old version of Glade.  Your version is for gtk2.  In gtk3 they phased out the vbox and hbox.  Now there's just a Gtk::box with a property of vertical or horizontal.  

The good news is that the latest versions of glade are really good.  I think I'm using glade 3.16.  Switch to that, and I'm sure you'll be happy.  The new one is really easy to use too.  I love it.

Keep using ruby 2.3 that's good.  Upgrade your glade to a gtk3 version.  And I'm updating visualruby very regularly, so I'm on 3.0.20 now.  There's no problem updating that too.  just use:

gem install visualruby

Let me know how it goes,

Eric

**Comment by rubycoder** [comment]
Hi Eric,

Thanks for your lightning fast response!

I upgraded to Glade 3.14.2, which is the latest prebuilt Windows binary, and it works fine.

> > I'm updating visualruby very regularly

I noticed that.  Many of the open source projects I take a look at seem semi-dormant, so it's nice to see all the activity in VisualRuby.  I updated to 3.0.20.

I've been programming Ruby for a long time, and I've been frustrated by the scarcity of cross-platform GUI libraries.  I'm really looking forward to working with VisualRuby.

> > Let me know how it goes

Will do.  Is there a mailing list or discussion group for questions, etc?

Best regards,

Wayne

**Comment by Beagle123** [comment]
Thanks Wayne:

Keep me posted on your project.  Give me an idea of what you're working on.  I'd really like to see more projects developed in visualruby.

I'm working on a front-end to yard.  If you're not familiar with yard, its a replacement for rdoc, and is a better documenting tool.

https://github.com/Beagle123/my_yard

Its at a very early stage, but I assure you it will be a good working program in a couple of weeks.  In fact, it will be incorporated into vr soon.

Best,
Eric

**Comment by rubycoder** [comment]
Hi Eric,

I notice that VisualRuby isn't listed as a GUI Framework on rubytoolbox:
https://www.ruby-toolbox.com/categories/GUI_Frameworks

Oddly, there are some VisualRuby related entries, but they're not categorized
https://www.ruby-toolbox.com/search?utf8=%E2%9C%93&q=visualruby

Rubytoolbox is one of the first places I look for a Ruby library, so it should improve VisualRuby's visibility if it were correctly categorized.

What I'm currently working on is a calculator program (+ - \* / sqrt etc.) with 1000 significant digits using Ruby's BigDecimal library.  I'm doing this for 2 reasons

1) Both the logic and the GUI should be relatively simple.  I like to start with a simple project when learning a new library.
2) We have a young daughter who is very interested in mathematics.  One of her current interests is the decimal representation of rational and irrational numbers.   Very few calculators (either physical or software) support more than 16 significant digits, which isn't nearly enough for the really interesting numbers.

I should point out that I have very limited time for this project at the moment, so my progress will be a bit slow.  I'll keep you posted.

Best regards,
Wayne
