### ISSUE TITLE
VisualRuby crashes when "Open Project" is clicked

### ISSUE THREAD

**Issue by rubycoder** [Beagle123/visualruby#32]
VisualRuby 3.0.15 had been working fine.  As soon as I switched to 3.0.20, clicking the "Open Project" button would often cause VisualRuby to crash (the VisualRuby window disappears without any apparent error message, and the command prompt window displays a stack trace and other debug info.)

The crash doesn't happen every time I click Open Project, but it happens quite often.  If I just click Open Project, then click it again, then again I can't click more than 3 or 4 times before seeing this crash.  It does not seem to be a particular project that's causing the crash.

I uninstalled 3.0.20 and went back to 3.0.15.  I did Open Project 20 times in a row, with no crash or other problems.  So apparently this behavior was introduced between 3.0.15 and 3.0.20, as I don't know anything that changed besides the VisualRuby version.

I've seen several different stack traces on these crashes.  The attached file contains two of them.

Ruby 2.3.0-p0 on Windows 7 Professional SP 1 64 bit

Let me know if I can provide further info. 

[Open Project crash.txt](https://github.com/Beagle123/visualruby/files/363088/Open.Project.crash.txt)

**Comment by Beagle123** [comment]
Hi:

Thanks for the report.  I'm really not sure what to tell you.  I know that some weird behavior happens, but the messages that it spits out is no help.

There is definitely a bug somewhere, but I believe that it is in GTK or ruby.  The program sometimes crashes when I manipulate the VR::TreeView object, but the code I use is very simple, and shouldn't be causing errors.  Also, the same code worked fine with gtk2.

I know that it will crash regularly after you do a "save as" then delete the old file.  Yet the delete, and "save as" work perfectly on their own.  There is a memory leak somewhere, and my program should have the potential to make the leak.

The open project works fine on my linux machine, so it will be even more difficult for me to debug.  

I'll have this in mind, but I'm not sure what to do.  Right now, I just restart the program.  But it only happens to me once in a while.

Sorry I can't be of more help,
Eric

**Comment by rubycoder** [comment]
Hi Eric,

Thanks for your very prompt response!

I should have mentioned that I'm running the 32-bit version of Ruby, because the rubyinstaller.org site cautions that the 64-bit version is "relatively new" on Windows.  I just now installed the 64-bit Ruby and tried to recreate this problem.

I did "Open Project" 3 times in a row.  The 3rd time I clicked Open Project, the VisualRuby window immediately disappeared, just like on 32-bit.  However,  no additional info was written to the command prompt window, just the usual

`C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb: line 162
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb: line 162
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed`
etc.

I tried again, and got exactly the same behaviour as above on the 3rd try.

I tried again, and this time I was able to do Open Project more than 20 times with no problems.

Not sure what to make of this, as the problem is still there (intermittently), but the symptoms are different (no command prompt output)

You mentioned a memory leak.  This particular issue doesn't sound like a memory leak to me.  I wouldn't expect a memory leak to cause a crash unless it had used up all the memory.  In this case, the crash often happens within 2 seconds of starting the program, so there probably isn't time to use up all the memory, and if this were the cause I'd expect to see a NoMemoryError exception.

I'm seeing another situation where VisualRuby abruptly quits (with either 32-bit or 64-bit Ruby) when I click Open Project and try to open "examples/active_record".  But I'm pretty sure this one is different as it's completely recreatable, and the command window shows

`C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/class_loader.rb:54:in 'path2class': undefined class/module VR::SimpleComboBoxEntry`

which looks like a simple error in the active_record example.

I've appended the full command window output below.

Thanks,
Wayne

`C:\Users\wayne>vr
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb: line 551
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb: line 551
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb: line 551
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb: line 551
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/collection-reader.rb: line 28
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/collection-reader.rb: line 28
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/collection-reader.rb: line 28
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/collection-reader.rb: line 28
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb: line 551
   Gtk-WARNING **:Allocating size to GtkBox 00000000050905D0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/callable-info.rb: line 36
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/callable-info.rb: line 36
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/callable-info.rb: line 36
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/callable-info.rb: line 36
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb: line 166
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb: line 166
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb: line 166
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb: line 166
   Gdk-CRITICAL **:gdk_pixbuf_get_from_surface: assertion 'surface != NULL' failed
C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/class_loader.rb:54:in 'path2class': undefined class/module VR::SimpleComboBoxEntry
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/class_loader.rb:54:in 'resolve'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/class_loader.rb:46:in 'find'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/class_loader.rb:28:in 'load'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:396:in 'resolve_class'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in 'visit_Psych_Nodes_Mapping'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in 'visit'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in 'accept'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in 'accept'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:338:in 'block in revive_hash'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in 'each'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in 'each_slice'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in 'revive_hash'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:374:in 'revive'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:208:in 'visit_Psych_Nodes_Mapping'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in 'visit'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in 'accept'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in 'accept'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in 'visit_Psych_Nodes_Document'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in 'visit'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in 'accept'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in 'accept'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych/nodes/node.rb:38:in 'to_ruby'
         from C:/Ruby/Ruby230p0x64/lib/ruby/2.3.0/psych.rb:253:in 'load'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/SavableClass.rb:13:in 'load_yaml'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/src/main/VR_Main.rb:256:in 'load_state'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/src/main/VR_Main.rb:90:in 'load_project'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/src/main/VR_Main.rb:100:in 'toolOpenFolder__clicked'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb:167:in 'call'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb:167:in 'block (3 levels) in parse_signals'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:114:in 'invoke'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:114:in 'block in define_singleton_method'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/lib/GladeGUI.rb:432:in 'show_glade'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/vr:22:in 'load_everything'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/vr:42:in 'block in <top (required)>'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:114:in 'invoke'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.0.8-x64-mingw32/lib/gobject-introspection/loader.rb:114:in 'block in define_singleton_method'
         from C:/Ruby/Ruby230p0x64/lib/ruby/gems/2.3.0/gems/visualruby-3.0.20/vr:45:in '<top (required)>'
         from C:/Ruby/Ruby230p0x64/bin/vr:23:in 'load'
         from C:/Ruby/Ruby230p0x64/bin/vr:23:in '<main>'`

**Comment by rubycoder** [comment]
I did some more testing, did an "Open Project" and got the crash, and saw this in the console output:

`[BUG] rb_gc_mark(): 0x00000002d1ff68 is T_NONE`

(see attached file for full output)

Ruby code should not be able to generate this error, so I agree with you that the bug seems to be in some native code, probably GTK or Ruby.

Wayne

[bug rb_gc_mark.txt](https://github.com/Beagle123/visualruby/files/364686/bug.rb_gc_mark.txt)

**Comment by Beagle123** [comment]
Hi Wayne:

You did uncover a problem with the active_record example.  It had a .vr_settings file that was very old and contained a reference to VR::SimpleComboBox which no longer exists.  I wrote VR::SimpleComboBox because Glade had a problem with simple text combo boxes, but now they have a TextComboBox that is awesome and works perfectly.   Therefore I deleted the SimpleComboBox class, but a reference remained in the active_record example.

To fix this, simply delete the .vr_settings hidden file in the active_record directory.  However, vr will no longer recognize this folder as a project when the vr_settings file is gone, so you will need to click "New Project" and add it again.  I've fixed it in my copy and released v3.0.21 which will also fix the problem.

Its pretty cool that that settings file existed so long without any problems.  It dated way back to when there was no separate global file (maybe 5 years).  But that's the cool thing about the way I handle settings.  The settings can have variables added or taken away without any errors or updating.  Everything runs perfectly unless you refer to a class that it can't find which happened here.  The only reason that we encountered this error was because I had to make a "work around" to glade's bug.  Normally that file could have existed forever.  It just contained several references that were being ignored.

I've tried to track down those other errors in the past, and I'm afraid that I'm not qualified to debug ruby or gtk.  These versions are relatively new, so maybe it will get fixed.

My code is fairly simple and has worked for a long time.  Also, the fact that errors happen differently each time leads me to believe that there's a leak somewhere.

Thanks for catching that problem for me.

Best,
Eric

**Comment by rubycoder** [comment]
Hi Eric,

> >  Thanks for catching that problem for me.

I'm glad my report was useful.

> >  Its pretty cool that that settings file existed so long without any problems

That _is_ impressive!  It sounds like your approach to settings is robust and resilient.  I've seen too many systems designed with lots of interdependent pieces which work as long as every piece works perfectly, but if there's a little glitch anywhere, the whole thing collapses like a house of cards.  A robust approach is important for settings, as in this case, where a settings file is created many years ago, and we'd like it to keep working (unchanged) as other things change around it.

> > I'm afraid that I'm not qualified to debug ruby or gtk

Back in the day I was a full-time C programmer for a decade, and I worked on bugs like this a lot.  Even when I was in practice from doing this all the time, fixing bugs like this wasn't easy.

Best regards,

Wayne
