### ISSUE TITLE
Slow VR startup when current directory contains many files

### ISSUE THREAD

**Issue by rubycoder** [Beagle123/visualruby#35]
For a while now I've been investigating an interesting issue:

VisualRuby has been running well for me on Windows 7.  I've begun migrating my development from my old laptop to a new one, both running Windows 7 (the same version and patches).  A week ago I tried running VisualRuby on the new laptop for the first time (using the same version of Ruby and VisualRuby as on the old system.)

When I ran VisualRuby, it displayed the VisualRuby splash screen, as usual.  But VisualRuby hung with the splash screen displayed for 10 minutes and 30 seconds, before the actual VisualRuby main window appeared.  Once the main window appeared, it responded quickly and seemed perfectly functional.

I tried the newest versions of Ruby and VisualRuby (3.0.22), but the above hang still occurred.  This problem is completely re-creatable, and I recreated it 6 or 7 times in a row.  The software on these two laptops is virtually identical, so it seemed odd that the hang occurs every time on the new laptop, but never on the old one.

After some investigation, I noticed that on the new system the current directory for the command prompt (cmd.exe) happened to be C:/Windows/System32, but on the old system it was some other directory.  I tried changing the current directory on the new system, and the hang went away.  I tried changing the current directory to C:/Windows/System32 on the old system, and now VisualRuby displayed the hang on the old system.

So, I saw the hang if and apparently only if the current directory was C:/Windows/System32.

Debugging VisualRuby while the hang was going on (VisualRuby was constantly using 100% of one CPU core during this time), I saw that every time I paused execution, the stack was in the add_file method `[FileTreeView.rb line 102] (VR::FileTreeView)`

The C:/Windows/System32 directory has over 2,900 files in its top level (that is, not counting files within subdirectories).  That, and the fact that we were always in add_file led me to suspect that the large number of files was the cause.

I created a new empty directory, set that as my current directory, then ran "vr".  It started up immediately with no hang.  I then created 1,000 empty files in this directory. (The Ruby program I used to create these is appended below).  I than ran "vr" and it hung for several minutes before starting up.

I recreated this test on Ubuntu 16.04 with the same results as above: VisualRuby starts immediately if the current directory is empty, but hangs for minutes if I create 1,000 files in that directory.

In https://github.com/Beagle123/visualruby/issues/32 you mentioned an intermittent problem in VR::TreeView.  I'm seeing this in VR::FileTreeView, but I wonder if these two issues might be related?

Here's the simple program I put together to create lots of 0 length files in the current directory.  Run it like this:

ruby filegen.rb 1000

```
# filegen.rb - generate 0 length files in the current directory
# usage:
#   ruby filegen.rb 10 # generate 10 files, 'testfile_0001' through 'testfile_0010'
#   ruby filegen.rb 20 100 # generate 20 files, 'testfile_0100' through 'testfile_0119'

number_of_files = ARGV[0].to_i
starting_file   = (ARGV[1] || 1).to_i

(0...number_of_files).each do |num|
  open(sprintf('testfile_%04d', starting_file+num), 'w') {}   # the block immediately closes the file
end
```

**Comment by Beagle123** [comment]
Hi Wayne:

Actually this is due to the fact that ruby's Dir.glob() method takes a long time to parse all those files.  And I think its very slow on windows.  Its designed to open reasonable sized projects.  I can see how it would be super slow on a directory like win32.

If you just keep the home/visualruby as the working directory, it should remain fast.

E

**Comment by Beagle123** [comment]
Come to think of it, I think its actually the Gtk::Listview building the tree that causes it to be slow.  It seems to slow down exponentially meaning that it is checking the whole tree each time a new node is added.

**Comment by rubycoder** [comment]
Hi Eric,

Thank you for your comments!

Several questions spring to mind, but let me start with this one:

On startup, why does VisualRuby build a TreeView (or ListView) of the contents of the working directory?  When VisualRuby starts up, I usually see a TreeView of .../visualruby/examples/alert_box (or some other project).  I don't think I've ever seen a TreeView of the working directory.

Why take the time to build a TreeView of the working directory if it isn't displayed?

Best regards,
Wayne

**Comment by Beagle123** [comment]
Hey Wayne:

So this is how it works:

First, it tries to open a passed argument as the current project:

```
@proj_path = argv[0] ? argv[0] : Dir.pwd
```

So if you run this:

vr /home/eric/visualruby/path_to_project

will open that folder.

If that folder isn't a valid project (it doesn't have a .vr_settings.yaml file) then it will fall back to the current directory, Dir.pwd.

If Dir.pwd isn't valid it will try the default project saved in the visualruby/.global_settings.yaml file.

If the default project (which is the last open project) isn't valid, it will open the alert_box example project.

Hope that helps.  THe code is in src/main/VR_Main.rb

Have a good night,
Eric

**Comment by rubycoder** [comment]
Hey Eric,

Super!!!  Thanks for the pointer to the relevant code.  I'll take a look at it...tomorrow :-)

Good night,

Wayne

**Comment by rubycoder** [comment]
Hi Eric,

I did some timing tests on how long it took VisualRuby to start up, depending on the number of files in the working directory.  I ran the tests on Ubuntu 16.04 (on VirtualBox), VisualRuby 3.0.22, ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux].

This list shows number of files and startup time in seconds (until the main window appears)

```
   0   2
 100   4
 200   7
 300  13
 400  23
 500  34
 700  66
1000 149
```

I timed these by hand with a stopwatch, and only ran each test once or twice.  I didn't try to do careful, precise benchmarking, but just quickly gathered some approximate data.  This data is  consistent with the time being proportional to the square of the number of files.  In particular, for the values between 300 and 700, when I divide the time by n squared (and move the decimal point to a reasonable place) I get 1.22, 1.31, 1.28, 1.31 which is pretty good for such approximate data.

Do I understand correctly that this is just the way Gtk::Listview works, so there isn't much we can do about it?  That would be disappointing.  I was planning on writing a VisualRuby project that needs to display lists of 1000 or more items, and if it takes 2 minutes to display them, the program will be pretty unusable.

**Comment by Beagle123** [comment]
I don't have an exact answer at this moment. but I think if you put the files in a folder, it would really speed things up because the file tree view only scans open folders.  However when you click the folder with 1000 files in it, it would have a big pause.  I'll look at the code when I get time.

E

**Comment by Beagle123** [comment]
It seems like when you load a normal listview its much faster.  I know that the Gtk::Listview can easily handle 1000 rows.
