### ISSUE TITLE
Error require pango.so on Windows - Fixed

### ISSUE THREAD

**Issue by rubycoder** [Beagle123/visualruby#41]
FYI - In case anyone else is seeing this issue on Windows:

Using VisualRuby 3.1.3 on Windows gives the following error:

	C:/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pango.so

Some investigation shows that updating the cairo gem to 1.15.3 or later resolves this issue.
https://github.com/ruby-gnome2/ruby-gnome2/issues/960

**Comment by Beagle123** [comment]
Hi Wayne:

That's great news because I think that will automatically update when everyone updates to visualruby 3.1.5

**Comment by rubycoder** [comment]
Hi Eric,

>> Sorry for the late response.

No worries!  I know what it's like to be busy/sidetracked/whatever.

>> I think that will automatically update when everyone updates to visualruby 3.1.5

I tested this, and it doesn't automatically update:

My Windows 10 Home system had VisualRuby 3.0.22 installed (because I don't do development on that system, I mostly use it to test stuff).  I updated to 3.1.6, but the cairo gem was at 1.15.2 before and after, and the pango.so error still occurs:

	C:\Users\wayne>ruby -v
	ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]

	C:\Users\wayne>gem list

	*** LOCAL GEMS ***

	actioncable (5.0.0.1)
	actionmailer (5.0.0.1, 2.3.18)
	actionpack (5.0.0.1, 2.3.18)
	actionview (5.0.0.1)
	activejob (5.0.0.1)
	activemodel (5.0.0.1)
	activerecord (5.0.0.1, 2.3.18)
	activeresource (2.3.18)
	activesupport (5.0.0.1, 2.3.18)
	arel (7.1.2)
	atk (3.0.8 x86-mingw32)
	bigdecimal (1.2.8)
	builder (3.2.2)
	bundler (1.13.1)
	cairo (1.15.2 x86-mingw32)
	cairo-gobject (3.0.8 x86-mingw32)
	chipmunk (6.1.3.4)
	coderay (1.1.1)
	coffee-rails (4.2.1)
	coffee-script (2.4.1)
	coffee-script-source (1.10.0)
	concurrent-ruby (1.0.2)
	debase (0.2.2.beta8, 0.2.1)
	debase-ruby_core_source (0.9.1)
	debug_inspector (0.0.2)
	did_you_mean (1.0.0)
	erubis (2.7.0)
	execjs (2.7.0)
	fakefs (0.9.1)
	gdk3 (3.0.8 x86-mingw32)
	gdk_pixbuf2 (3.0.8 x86-mingw32)
	gio2 (3.0.8 x86-mingw32)
	glib2 (3.0.8 x86-mingw32)
	globalid (0.3.7)
	gobject-introspection (3.0.8 x86-mingw32)
	gosu (0.11.1 x86-mingw32, 0.10.8 x86-mingw32)
	gosu-examples (1.0.4)
	gtk3 (3.0.8 x86-mingw32)
	gtksourceview3 (3.0.8 x86-mingw32)
	i18n (0.7.0)
	io-console (0.4.5)
	jbuilder (2.6.0)
	jquery-rails (4.2.1)
	json (2.0.2, 1.8.3)
	loofah (2.0.3)
	mail (2.6.4)
	method_source (0.8.2)
	mime-types (3.1)
	mime-types-data (3.2016.0521)
	mini_portile2 (2.1.0)
	minitest (5.9.1, 5.8.3)
	multi_json (1.12.1)
	net-telnet (0.1.1)
	nio4r (1.2.1)
	nokogiri (1.6.8.1 x86-mingw32, 1.6.8 x86-mingw32)
	pango (3.0.8 x86-mingw32)
	pkg-config (1.1.7)
	power_assert (0.2.6)
	pr_geohash (1.0.0)
	pry (0.10.4)
	psych (2.0.17)
	puma (3.6.0)
	rack (2.0.1, 1.1.6)
	rack-test (0.6.3)
	rails (5.0.0.1)
	rails-dom-testing (2.0.1)
	rails-html-sanitizer (1.0.3)
	railties (5.0.0.1)
	rake (11.3.0, 10.4.2)
	rdoc (4.2.1)
	require_all (1.3.3)
	rmagick (2.16.0)
	rsolr (1.1.2)
	rsvg2 (3.0.8 x86-mingw32)
	ru2 (2.1.4)
	ruby-debug-ide (0.6.1.beta2)
	ruby-prof (0.15.9)
	rubygems-update (2.6.7)
	sass (3.4.22)
	sass-rails (5.0.6)
	slop (3.6.0)
	sprockets (3.7.0)
	sprockets-rails (3.2.0)
	sqlite3 (1.3.11 x86-mingw32)
	sunspot (2.2.6)
	sunspot_rails (2.2.6)
	sunspot_solr (2.2.6)
	test-unit (3.1.5)
	thor (0.19.1)
	thread_safe (0.3.5)
	tilt (2.0.5)
	turbolinks (5.0.1)
	turbolinks-source (5.0.0)
	tzinfo (1.2.2)
	tzinfo-data (1.2016.7)
	uglifier (3.0.2)
	visualruby (3.0.22)
	web-console (3.3.1)
	websocket-driver (0.6.4)
	websocket-extensions (0.1.2)

	C:\Users\wayne>gem install visualruby
	Fetching: glib2-3.1.1-x86-mingw32.gem (100%)
	Successfully installed glib2-3.1.1-x86-mingw32
	Fetching: gobject-introspection-3.1.1-x86-mingw32.gem (100%)
	Successfully installed gobject-introspection-3.1.1-x86-mingw32
	Fetching: gio2-3.1.1-x86-mingw32.gem (100%)
	Successfully installed gio2-3.1.1-x86-mingw32
	Fetching: atk-3.1.1-x86-mingw32.gem (100%)
	Successfully installed atk-3.1.1-x86-mingw32
	Fetching: pango-3.1.1-x86-mingw32.gem (100%)
	Successfully installed pango-3.1.1-x86-mingw32
	Fetching: gdk_pixbuf2-3.1.1-x86-mingw32.gem (100%)
	Successfully installed gdk_pixbuf2-3.1.1-x86-mingw32
	Fetching: cairo-gobject-3.1.1-x86-mingw32.gem (100%)
	Successfully installed cairo-gobject-3.1.1-x86-mingw32
	Fetching: gdk3-3.1.1-x86-mingw32.gem (100%)
	Successfully installed gdk3-3.1.1-x86-mingw32
	Fetching: rsvg2-3.1.1-x86-mingw32.gem (100%)
	Successfully installed rsvg2-3.1.1-x86-mingw32
	Fetching: gtk3-3.1.1-x86-mingw32.gem (100%)
	Successfully installed gtk3-3.1.1-x86-mingw32
	Fetching: gtksourceview3-3.1.1-x86-mingw32.gem (100%)
	Successfully installed gtksourceview3-3.1.1-x86-mingw32
	Fetching: visualruby-3.1.6.gem (100%)
	Successfully installed visualruby-3.1.6
	Parsing documentation for glib2-3.1.1-x86-mingw32
	Installing ri documentation for glib2-3.1.1-x86-mingw32
	Parsing documentation for gobject-introspection-3.1.1-x86-mingw32
	Installing ri documentation for gobject-introspection-3.1.1-x86-mingw32
	Parsing documentation for gio2-3.1.1-x86-mingw32
	Installing ri documentation for gio2-3.1.1-x86-mingw32
	Parsing documentation for atk-3.1.1-x86-mingw32
	Installing ri documentation for atk-3.1.1-x86-mingw32
	Parsing documentation for pango-3.1.1-x86-mingw32
	Installing ri documentation for pango-3.1.1-x86-mingw32
	Parsing documentation for gdk_pixbuf2-3.1.1-x86-mingw32
	Installing ri documentation for gdk_pixbuf2-3.1.1-x86-mingw32
	Parsing documentation for cairo-gobject-3.1.1-x86-mingw32
	Installing ri documentation for cairo-gobject-3.1.1-x86-mingw32
	Parsing documentation for gdk3-3.1.1-x86-mingw32
	Installing ri documentation for gdk3-3.1.1-x86-mingw32
	Parsing documentation for rsvg2-3.1.1-x86-mingw32
	Installing ri documentation for rsvg2-3.1.1-x86-mingw32
	Parsing documentation for gtk3-3.1.1-x86-mingw32
	Installing ri documentation for gtk3-3.1.1-x86-mingw32
	Parsing documentation for gtksourceview3-3.1.1-x86-mingw32
	Installing ri documentation for gtksourceview3-3.1.1-x86-mingw32
	Parsing documentation for visualruby-3.1.6
	Installing ri documentation for visualruby-3.1.6
	Done installing documentation for glib2, gobject-introspection, gio2, atk, pango, gdk_pixbuf2, cairo-gobject, gdk3, rsvg2, gtk3, gtksourceview3, visualruby after 12 seconds
	12 gems installed

	C:\Users\wayne>gem list

	*** LOCAL GEMS ***

	actioncable (5.0.0.1)
	actionmailer (5.0.0.1, 2.3.18)
	actionpack (5.0.0.1, 2.3.18)
	actionview (5.0.0.1)
	activejob (5.0.0.1)
	activemodel (5.0.0.1)
	activerecord (5.0.0.1, 2.3.18)
	activeresource (2.3.18)
	activesupport (5.0.0.1, 2.3.18)
	arel (7.1.2)
	atk (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	bigdecimal (1.2.8)
	builder (3.2.2)
	bundler (1.13.1)
	cairo (1.15.2 x86-mingw32)
	cairo-gobject (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	chipmunk (6.1.3.4)
	coderay (1.1.1)
	coffee-rails (4.2.1)
	coffee-script (2.4.1)
	coffee-script-source (1.10.0)
	concurrent-ruby (1.0.2)
	debase (0.2.2.beta8, 0.2.1)
	debase-ruby_core_source (0.9.1)
	debug_inspector (0.0.2)
	did_you_mean (1.0.0)
	erubis (2.7.0)
	execjs (2.7.0)
	fakefs (0.9.1)
	gdk3 (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	gdk_pixbuf2 (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	gio2 (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	glib2 (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	globalid (0.3.7)
	gobject-introspection (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	gosu (0.11.1 x86-mingw32, 0.10.8 x86-mingw32)
	gosu-examples (1.0.4)
	gtk3 (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	gtksourceview3 (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	i18n (0.7.0)
	io-console (0.4.5)
	jbuilder (2.6.0)
	jquery-rails (4.2.1)
	json (2.0.2, 1.8.3)
	loofah (2.0.3)
	mail (2.6.4)
	method_source (0.8.2)
	mime-types (3.1)
	mime-types-data (3.2016.0521)
	mini_portile2 (2.1.0)
	minitest (5.9.1, 5.8.3)
	multi_json (1.12.1)
	net-telnet (0.1.1)
	nio4r (1.2.1)
	nokogiri (1.6.8.1 x86-mingw32, 1.6.8 x86-mingw32)
	pango (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	pkg-config (1.1.7)
	power_assert (0.2.6)
	pr_geohash (1.0.0)
	pry (0.10.4)
	psych (2.0.17)
	puma (3.6.0)
	rack (2.0.1, 1.1.6)
	rack-test (0.6.3)
	rails (5.0.0.1)
	rails-dom-testing (2.0.1)
	rails-html-sanitizer (1.0.3)
	railties (5.0.0.1)
	rake (11.3.0, 10.4.2)
	rdoc (4.2.1)
	require_all (1.3.3)
	rmagick (2.16.0)
	rsolr (1.1.2)
	rsvg2 (3.1.1 x86-mingw32, 3.0.8 x86-mingw32)
	ru2 (2.1.4)
	ruby-debug-ide (0.6.1.beta2)
	ruby-prof (0.15.9)
	rubygems-update (2.6.7)
	sass (3.4.22)
	sass-rails (5.0.6)
	slop (3.6.0)
	sprockets (3.7.0)
	sprockets-rails (3.2.0)
	sqlite3 (1.3.11 x86-mingw32)
	sunspot (2.2.6)
	sunspot_rails (2.2.6)
	sunspot_solr (2.2.6)
	test-unit (3.1.5)
	thor (0.19.1)
	thread_safe (0.3.5)
	tilt (2.0.5)
	turbolinks (5.0.1)
	turbolinks-source (5.0.0)
	tzinfo (1.2.2)
	tzinfo-data (1.2016.7)
	uglifier (3.0.2)
	visualruby (3.1.6, 3.0.22)
	web-console (3.3.1)
	websocket-driver (0.6.4)
	websocket-extensions (0.1.2)

	C:\Users\wayne>vr
	c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pango.so (LoadError)
			from c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/pango-3.1.1-x86-mingw32/lib/pango.rb:20:in `rescue in <top (required)>'
			from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/pango-3.1.1-x86-mingw32/lib/pango.rb:16:in `<top (required)>'
			from c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/gdk3-3.1.1-x86-mingw32/lib/gdk3.rb:20:in `<top (required)>'
			from c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/gtk3-3.1.1-x86-mingw32/lib/gtk3.rb:19:in `<top (required)>'
			from c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/ruby/Ruby231p112/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from c:/Ruby/Ruby231p112/lib/ruby/gems/2.3.0/gems/visualruby-3.1.6/vr:1:in `<top (required)>'
			from c:/Ruby/Ruby231p112/bin/vr:22:in `load'
			from c:/Ruby/Ruby231p112/bin/vr:22:in `<main>'

**Comment by rubycoder** [comment]
As expected, explicitly installing the latest cairo gem (1.15.5) avoids the pango.so error

**Comment by Beagle123** [comment]
Installing visualruby 3.1.7 or later fixes this!!

Thanks,
Eric
