### ISSUE TITLE
cairo.so Issue on Win10 64 Bit

### ISSUE THREAD

**Issue by rtuz2th** [Beagle123/visualruby#45]
Hi,
I'm also facing the issue that I get the issue that the cairo.so is not found. This is what it looks like:

C:\Users\rtuz2th>vr
C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cairo.so (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cairo-1.15.5-x64-mingw32/lib/cairo.rb:48:in `rescue in <top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/cairo-1.15.5-x64-mingw32/lib/cairo.rb:44:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/glib2-3.1.1-x64-mingw32/lib/glib2.rb:112:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gobject-introspection-3.1.1-x64-mingw32/lib/gobject-introspection.rb:17:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gtk3-3.1.1-x64-mingw32/lib/gtk3.rb:17:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/visualruby-3.1.11/vr:1:in `<top (required)>'
        from C:/Ruby24-x64/bin/vr:23:in `load'
        from C:/Ruby24-x64/bin/vr:23:in `<main>'

I'm running Win 10 64 Bit, got Glade 3.8.5 installed. Is there any fix or workaround for this?

**Comment by rubycoder** [comment]
I would try with Ruby 2.3.x rather than Ruby 2.4.x

**Comment by rtuz2th** [comment]
Thanks for your superfast answer! Worked for me!
